version: "3"
services:
  web:
    build: .
    ports:
      - "3000:3000"
    links:
      - mysql
    depends_on:
      - mysql
  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
    command: --init-file /usr/app/init.sql
    volumes:
      - ./init.sql:/usr/app/init.sql
